### PR TITLE
Describe rnpm install in actions section

### PR DESCRIPTION
**Pull request by grabbou**

### CODE REVIEW

**Comment by geof90** [comment]
Is this going to be published to NPM soon? Not rushing, was just curious if anything is blocking the release right now :)

**Comment by grabbou** [comment]
Try upgrading rnpm. Of course, its version didn't change, but since we use semver, you will get newer rnpm-plugin-link dependency that should have this (1.5.5 is the latest one). We haven't announced all these things publicly since there's quite a lot going on with test suites etc.

**Comment by geof90** [comment]
Right, but rnpm-plugin-link doesnt have the install command, only rnpm-plugin-install. And the latest version on NPM doesnt have the install plugin in the dependencies so that wouldn't have this change.

**Comment by grabbou** [comment]
Ah, sorry, to early here. You are right. Re: that, we will release right after tests are done :)

**Pull request merged**
