### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Kureev**
subj

### CODE REVIEW

**Comment by Kureev** [comment]
сс @grabbou

**Comment by Kureev** [comment]
[Blocked by codeclimate eslint 2.x+ support](https://github.com/codeclimate/codeclimate-eslint/issues/76)

**Comment by dblandin** [comment]
Hey @Kureev,

We just [released support for ESLint 2](https://codeclimate.com/changelog/574dc95efdd7dc0090002225) via an opt-in channel, which should unblock this PR!

Let me know if you have any questions.

**Comment by Kureev** [comment]
Awesome! I will give it a try and let you know!

**Pull request closed without merging**
